version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ${DATA_PATH:-sonarqube_data}/sqdata:/opt/sonarqube/data
      - ${DATA_PATH:-sonarqube_extensions}/sqext:/opt/sonarqube/extensions
      - ${DATA_PATH:-sonarqube_logs}/sqlog:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ${DATA_PATH:-postgresql}/pgsql:/var/lib/postgresql
      - ${DATA_PATH:-postgresql_data}/pgsqldata:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: