version: '3'
services:
  nextjs:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_URL}
    volumes:
      - ./app:/app
      - /app/node_modules
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '${NGINX_PORT:-80}:80'
    depends_on:
      - nextjs
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf